version: "3"

services:
  db:
    container_name: db
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PWD
      - MYSQL_DATABASE=${DB_USER}
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PWD
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/init-script:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db